
obj-$(CONFIG_FB_SC8825) := sprdfb_main.o sprdfb_panel.o sprdfb_dispc.o sprdfb_lcdc.o sprdfb_mcu.o sprdfb_rgb.o sprdfb_mipi.o sprdfb_i2c.o sprdfb_spi.o sprdfb_dsi.o
obj-$(CONFIG_FB_SC8825) += dsi/
obj-$(CONFIG_FB_SC8825) += spi/

obj-$(CONFIG_FB_LCD_NT35512_MIPI) += lcd_nt35512_mipi.o
obj-$(CONFIG_FB_LCD_NT35517_MIPI) += lcd_nt35517_mipi.o
