
obj-$(CONFIG_FB_SCX35) := sprdfb_main.o sprdfb_panel.o sprdfb_dispc.o sprdfb_mipi.o sprdfb_dsi.o sprdfb_chip_common.o sprdfb_chip_8830.o
obj-$(CONFIG_FB_SCX35) += dsi/

obj-$(CONFIG_FB_LCD_NT35512_MIPI) += lcd_nt35512_mipi.o
obj-$(CONFIG_FB_LCD_NT35517_MIPI) += lcd_nt35517_mipi.o
